name: recover_example
description: Demonstrates how to use the recover plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  recover:
    path: ../
  cupertino_icons: ^1.0.2
  uuid: 3.0.5
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NunitoSans
      fonts:
        - asset: res/fonts/NunitoSans-Black.ttf
          weight: 900
        - asset: res/fonts/NunitoSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: res/fonts/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: res/fonts/NunitoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: res/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: res/fonts/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: res/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: res/fonts/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: res/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: res/fonts/NunitoSans-Italic.ttf
          weight: 400
          style: italic
        - asset: res/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: res/fonts/NunitoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/fonts/NunitoSans-ExtraLight.ttf
          weight: 200
        - asset: res/fonts/NunitoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
