name: zendesk_flutter
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  intl: ^0.17.0
  flutter_html: ^2.2.1
  url_launcher: ^6.0.18

flutter:
  plugin:
    platforms:
      android:
        package: com.mytiki.zendesk_flutter
        pluginClass: ZendeskFlutterPlugin
      ios:
        pluginClass: ZendeskFlutterPlugin
