name: zendesk_flutter
description: flutter lib for zendesk api
version: 0.0.1
homepage: https://mytiki.com
repository: https://github.com/tiki/zendesk_flutter
issue_tracker: https://github.com/tiki/zendesk_flutter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/recover/res/images/pineapple-pizza.png
    - packages/recover/res/images/avocado.png
    - packages/recover/res/animation/creating.json
    - packages/recover/res/animation/loading.json
  fonts:
    - family: RecoverIcons
      fonts:
        - asset: packages/recover/res/fonts/RecoverIcons.ttf